namespace Cygnux.LSP.Infrastructure.Constants;

public static class StoredProcedureConstants
{
    public const string Usp_GetCustomer = "Usp_GetCustomer";
    public const string Usp_GetCustomer_new = "Usp_GetCustomer_new";
    public const string Usp_GetLsp = "Usp_GetLsp";
    public const string Usp_GetLsp_new = "Usp_GetLsp_new";
    public const string USP_GetLspDetail = "USP_GetLspDetail";
    public const string Usp_User = "Usp_User";
    public const string Usp_Role = "Usp_Role";
    public const string Usp_UserRole = "Usp_UserRole";
    public const string Usp_CustomerLsp = "Usp_CustomerLsp";
    public const string Usp_CustomerLspTat = "Usp_CustomerLspTat";
    public const string Usp_GetCustomerLsp = "Usp_GetCustomerLsp";
    public const string Usp_GetCustomerLsp_New = "Usp_GetCustomerLsp_New";
    public const string USP_GetCustomerLSPDetails = "USP_GetCustomerLSPDetails";
    public const string Usp_GetCustomerLspTat = "Usp_GetCustomerLspTat";
    public const string Usp_DownloadLspTatLspTat = "Usp_DownloadLspTatLspTat";
    public const string USP_GetCustomerLspTatDetails = "USP_GetCustomerLspTatDetails";
    public const string Usp_GetMappedLsp = "Usp_GetMappedLsp";
    public const string Usp_GetMappedCustomer = "Usp_GetMappedCustomer";
    public const string Usp_Customer = "Usp_Customer";
    public const string Usp_Lsp = "Usp_Lsp";
    public const string Usp_Menu = "Usp_Menu";
    public const string Usp_Docket = "Usp_Docket";
    public const string USP_DocketStatusUpdate_Single = "USP_DocketStatusUpdate";
    public const string Usp_GetDocket = "Usp_GetDocket";
    public const string Usp_GetDocket_New = "Usp_GetDocket_New";
    public const string Usp_DownloadDocket = "Usp_DownloadDocket";
    public const string USP_GetDocketDetail = "USP_GetDocketDetail";
    public const string Usp_ImportDocket = "Usp_ImportDocket";
    public const string USP_TrackingList = "USP_MasterGeneralData";
    public const string USP_TranportModeData = "USP_TranportModeData";
    public const string USP_FetchDockData = "USP_FetchDockData";
    public const string Usp_RoleMenuPermission = "Usp_RoleMenuPermission";
    public const string Usp_GetMenuPermission = "Usp_GetMenuPermission";
    public const string USP_DeleteDocket = "USP_DeleteDocket";
    public const string USP_DeleteCancel = "USP_DeleteCancel";
    public const string USP_RejectCancel = "USP_RejectCancel";
    public const string USP_CustomerTATRootDropdown = "USP_CustomerTATRootDropdown";
    public const string USP_ValidateBulkUploadDocketData = "USP_ValidateBulkUploadDocketData";
    public const string PODUplaodDataFromExcel = "InsertPODUploadFromJson";
    public const string USP_InsertValiadateDocketData = "USP_InsertValiadateDocketData";
    public const string USP_ValidateDocketStatusData = "USP_ValidateDocketStatusData";
    public const string Usp_TrackingList = "Usp_TrackingList";
    public const string USP_UpdateDocketStatus = "USP_UpdateDocketStatus";
    public const string USP_CustomerDelete = "USP_CustomerDelete";
    public const string USP_ValidatePODJson = "USP_ValidatePODJson";
    public const string USP_GetUserList = "USP_GetUserList";
    public const string USP_InsertUpdateSinglePODUpload = "USP_InsertUpdateSinglePODUpload";
    public const string USP_RoleList = "USP_RoleList";
    public const string USP_DeleteCustomerDetails = "USP_DeleteCustomerDetails";
    public const string USP_DeleteLSPData = "USP_DeleteLSPData";
    public const string USP_DeleteLSPAndUpdateRelations = "USP_DeleteLSPAndUpdateRelations";
    public const string USP_Get_DeleteCustomerLspData = "USP_Get_DeleteCustomerLspData";
    public const string USP_Delete_CustomerLsp_Relations = "USP_Delete_CustomerLsp_Relations";
    public const string USP_Get_CustomerLspTat_Details = "USP_Get_CustomerLspTat_Details";
    public const string USP_Delete_CustomerLspTat_And_Dockets = "USP_Delete_CustomerLspTat_And_Dockets";
    public const string USP_DeleteUserAndRelations = "USP_DeleteUserAndRelations";
    public const string USP_DocketCount = "USP_DocketCount";
    public const string USP_DocketTransModeCount = "USP_DocketTransModeCount";
    public const string Usp_LspMappingCount = "Usp_LspMappingCount";
    public const string Usp_LspTatCount = "Usp_LspTatCount";
    public const string USP_CheckCustomerDetail = "USP_CheckCustomerDetail";
    public const string Usp_GetCustomers = "Usp_GetCustomers";
    public const string Usp_GetLsps = "Usp_GetLsps";
    public const string Usp_DownloadCustomer = "Usp_DownloadCustomer";
    public const string Usp_DownloadLsp = "Usp_DownloadLsp";
    public const string Usp_DownloadLspMapping = "Usp_DownloadLspMapping";
    public const string Usp_DownloadPOD = "Usp_DownloadPOD";
    public const string USP_ValidateLspTatData = "USP_ValidateLspTatData";
    public const string Usp_BulkCustomerLspTat = "Usp_BulkCustomerLspTat";


    public const string USP_OtpVerification= "USP_InsertLoginOTPverification";
    public const string USP_VerifyOTP = "USP_VerifyOTP";
    public const string USP_ValidateOTPUser = "USP_ValidateResendOTPRequest";
    public const string USP_UpdateOTPOnResend = "USP_UpdateOTPOnResend";
    public const string USP_PasswordResetORChange = "USP_PasswordResetORChange";
    public const string USP_GetUserId = "USP_GetUserId";
    public const string USP_GetResendLink = "USP_GetResendLink";
    public const string USP_ResendEmail = "USP_UpdateResendEmailOTPDetail";
    public const string USP_GetReqID = "USP_GetReqID";
    public const string USP_ForgetReq = "USP_UpdateForgotPasswordRequest";
    public const string Usp_CustomerCount = "Usp_CustomerCount";
    public const string Usp_LspCount = "Usp_LspCount";

    public const string USP_GetCity_Docket = "USP_GetCity_Docket";
    public const string USP_GetCity = "USP_GetCity";
    public const string USP_GetState = "USP_GetState";

}